# Generated by Django 5.1.4 on 2025-02-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(blank=True, default='profileImages/default.jpg', upload_to='profileImages'),
        ),
    ]
