# Generated by Django 5.1.4 on 2025-02-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='tasks.task'),
        ),
    ]
