# Generated by Django 5.1.4 on 2025-02-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_delete_employee_alter_taskdetails_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='tasks_asset/'),
        ),
    ]
