# Generated by Django 5.1.4 on 2025-02-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskdetails_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_asset/default.jpg', null=True, upload_to='tasks_asset/'),
        ),
    ]
